#!/usr/bin/env python3
"""Host-side parser and validator for shadow CPU enriched snapshots.

The parser consumes raw HDC command JSONL generated by
collect_cpu_enriched_shadow.ps1 and emits only shadow, not-for-training
artifacts. It never calls hdc and never mutates accepted datasets.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
from collections import Counter, defaultdict
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional, Tuple


SAFETY_FLAGS = {
    "training_performed": False,
    "adapter_changed": False,
    "net_baseline_changed": False,
    "accepted_ledger_changed": False,
    "scripts_modified": True,
    "collection_scripts_changed": False,
    "board_collection_executed": True,
    "formal_batch_collection": False,
    "mixed_contract_activated": False,
    "active_mixed_contract_changed": False,
    "production_baseline_claimed": False,
    "test_split_labels_raw_changed": False,
    "labels_changed": False,
    "splits_changed": False,
    "raw_artifacts_changed": False,
    "fault_injection_run": False,
    "daemon_started_or_stopped": False,
    "all_jsonl_used": False,
    "shadow_only": True,
    "not_for_training": True,
    "not_accepted": True,
    "active_contract": False,
    "production_baseline": False,
}


REQUIRED_ROW_FIELDS = [
    "timestamp",
    "run_id",
    "sample_index",
    "phase",
    "per_core_cpu_utilization",
    "hot_core_count",
    "top_cpu_process_identity",
    "top_cpu_thread_identity",
    "process_count",
    "thread_count",
    "runnable_queue_signal",
    "oversubscription_signal",
    "single_process_spin_marker",
    "multicore_saturation_signal",
    "process_distribution_signal",
    "thread_distribution_signal",
    "sampling_consistency",
    "source_refs",
    "safe_obs_flag",
    "candidate_visibility",
    "model_visible_summary",
    "trace_ref",
    "shadow_only",
    "not_for_training",
    "not_accepted",
    "active_contract",
    "production_baseline",
]

REQUIRED_SAMPLE_COMMANDS = [
    "proc_loadavg",
    "proc_stat",
    "proc_pressure_cpu",
    "proc_pid_stat_all",
]


def utc_now() -> str:
    return datetime.now(timezone.utc).isoformat()


def sha256_text(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8", errors="replace")).hexdigest()


def read_json(path: Path) -> Any:
    with path.open("r", encoding="utf-8-sig") as f:
        return json.load(f)


def write_json(path: Path, data: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as f:
        json.dump(data, f, indent=2, sort_keys=False)
        f.write("\n")


def write_md(path: Path, title: str, lines: Iterable[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as f:
        f.write(f"# {title}\n\n")
        for line in lines:
            f.write(f"{line}\n")


def read_jsonl(path: Path) -> List[Dict[str, Any]]:
    rows: List[Dict[str, Any]] = []
    with path.open("r", encoding="utf-8-sig") as f:
        for line_no, line in enumerate(f, 1):
            line = line.strip()
            if not line:
                continue
            try:
                row = json.loads(line)
            except json.JSONDecodeError as exc:
                raise ValueError(f"{path}:{line_no}: JSON decode failed: {exc}") from exc
            row["_line_no"] = line_no
            row["_raw_hash"] = sha256_text(line)
            rows.append(row)
    return rows


def write_jsonl(path: Path, rows: Iterable[Dict[str, Any]]) -> int:
    count = 0
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as f:
        for row in rows:
            f.write(json.dumps(row, ensure_ascii=False, sort_keys=False) + "\n")
            count += 1
    return count


def command_id(row: Dict[str, Any]) -> str:
    return f"raw:{row.get('sample_index')}:{row.get('command_label')}:{row.get('_line_no')}"


def rows_by_label_and_sample(rows: List[Dict[str, Any]]) -> Dict[Tuple[int, str], Dict[str, Any]]:
    out: Dict[Tuple[int, str], Dict[str, Any]] = {}
    for row in rows:
        sample_index = int(row.get("sample_index", -1))
        label = str(row.get("command_label", ""))
        out[(sample_index, label)] = row
    return out


def rows_by_label(rows: List[Dict[str, Any]], label: str) -> List[Dict[str, Any]]:
    return [r for r in rows if r.get("command_label") == label]


def required_command_completeness(raw_rows: List[Dict[str, Any]]) -> Dict[str, Any]:
    sample_indices = sorted(
        {
            int(r.get("sample_index", -1))
            for r in raw_rows
            if int(r.get("sample_index", -1)) >= 0 and r.get("command_label") in REQUIRED_SAMPLE_COMMANDS
        }
    )
    if not sample_indices:
        return {
            "status": "NEEDS_FIX",
            "sample_count": 0,
            "required_command_count": len(REQUIRED_SAMPLE_COMMANDS),
            "empty_required_rows": 0,
            "missing_required_rows": len(REQUIRED_SAMPLE_COMMANDS),
            "empty_required_snapshot_rate": 1.0,
            "missing_by_sample": {},
            "empty_by_sample": {},
        }
    by_sample: Dict[int, Dict[str, str]] = defaultdict(dict)
    for row in raw_rows:
        label = str(row.get("command_label", ""))
        if label not in REQUIRED_SAMPLE_COMMANDS:
            continue
        sample = int(row.get("sample_index", -1))
        if sample < 0:
            continue
        by_sample[sample][label] = str(row.get("stdout", ""))
    missing_by_sample: Dict[int, List[str]] = {}
    empty_by_sample: Dict[int, List[str]] = {}
    empty_required_rows = 0
    missing_required_rows = 0
    for sample in sample_indices:
        for label in REQUIRED_SAMPLE_COMMANDS:
            if label not in by_sample.get(sample, {}):
                missing_by_sample.setdefault(sample, []).append(label)
                missing_required_rows += 1
                continue
            text = by_sample[sample][label].strip()
            if not text:
                empty_by_sample.setdefault(sample, []).append(label)
                empty_required_rows += 1
    total_required = len(sample_indices) * len(REQUIRED_SAMPLE_COMMANDS)
    bad_rows = empty_required_rows + missing_required_rows
    return {
        "status": "PASS" if bad_rows == 0 else "NEEDS_REPAIR",
        "sample_count": len(sample_indices),
        "required_command_count": len(REQUIRED_SAMPLE_COMMANDS),
        "empty_required_rows": empty_required_rows,
        "missing_required_rows": missing_required_rows,
        "empty_required_snapshot_rate": round(bad_rows / total_required, 4) if total_required else 1.0,
        "missing_by_sample": {str(k): v for k, v in sorted(missing_by_sample.items())},
        "empty_by_sample": {str(k): v for k, v in sorted(empty_by_sample.items())},
    }


def parse_cpu_line(line: str) -> Optional[Tuple[str, List[int]]]:
    parts = line.strip().split()
    if not parts or not parts[0].startswith("cpu"):
        return None
    values: List[int] = []
    for token in parts[1:]:
        try:
            values.append(int(token))
        except ValueError:
            values.append(0)
    return parts[0], values


def parse_proc_stat(text: str) -> Dict[str, Any]:
    cpus: Dict[str, List[int]] = {}
    procs_running = None
    procs_blocked = None
    for line in text.splitlines():
        parsed = parse_cpu_line(line)
        if parsed:
            name, values = parsed
            cpus[name] = values
        elif line.startswith("procs_running"):
            try:
                procs_running = int(line.split()[1])
            except Exception:
                procs_running = None
        elif line.startswith("procs_blocked"):
            try:
                procs_blocked = int(line.split()[1])
            except Exception:
                procs_blocked = None
    return {"cpus": cpus, "procs_running": procs_running, "procs_blocked": procs_blocked}


def cpu_busy_idle(values: List[int]) -> Tuple[int, int]:
    idle = (values[3] if len(values) > 3 else 0) + (values[4] if len(values) > 4 else 0)
    total = sum(values)
    busy = total - idle
    return busy, total


def cpu_util_between(prev: List[int], cur: List[int]) -> Optional[float]:
    prev_busy, prev_total = cpu_busy_idle(prev)
    cur_busy, cur_total = cpu_busy_idle(cur)
    total_delta = cur_total - prev_total
    if total_delta <= 0:
        return None
    busy_delta = cur_busy - prev_busy
    return max(0.0, min(1.0, busy_delta / total_delta))


def parse_loadavg(text: str) -> Dict[str, Any]:
    parts = text.strip().split()
    out: Dict[str, Any] = {"raw": text.strip()}
    if parts:
        try:
            out["load1"] = float(parts[0])
        except ValueError:
            out["load1"] = None
    if len(parts) >= 4 and "/" in parts[3]:
        left, right = parts[3].split("/", 1)
        try:
            out["runnable"] = int(left)
            out["total_threads"] = int(right)
        except ValueError:
            out["runnable"] = None
            out["total_threads"] = None
    return out


def parse_psi(text: str) -> Dict[str, Any]:
    out: Dict[str, Any] = {"available": False, "some": None, "full": None, "raw": text.strip()}
    if "UNAVAILABLE" in text:
        return out
    for line in text.splitlines():
        parts = line.split()
        if not parts:
            continue
        key = parts[0]
        values: Dict[str, float] = {}
        for token in parts[1:]:
            if "=" not in token:
                continue
            k, v = token.split("=", 1)
            try:
                values[k] = float(v)
            except ValueError:
                pass
        if key in {"some", "full"}:
            out[key] = values
            out["available"] = True
    return out


def parse_proc_pid_stat_line(line: str) -> Optional[Dict[str, Any]]:
    line = line.strip()
    if not line or line == "UNAVAILABLE":
        return None
    left = line.find("(")
    right = line.rfind(")")
    if left < 1 or right <= left:
        return None
    pid_text = line[:left].strip()
    comm = line[left + 1 : right]
    rest = line[right + 1 :].strip().split()
    if len(rest) < 22:
        return None
    try:
        pid = int(pid_text)
        state = rest[0]
        utime = int(rest[11])
        stime = int(rest[12])
        starttime = int(rest[19]) if len(rest) > 19 else None
    except ValueError:
        return None
    return {
        "pid": pid,
        "comm": comm,
        "state": state,
        "utime": utime,
        "stime": stime,
        "cpu_ticks": utime + stime,
        "starttime": starttime,
    }


def parse_pid_stat_all(text: str) -> Dict[int, Dict[str, Any]]:
    out: Dict[int, Dict[str, Any]] = {}
    for line in text.splitlines():
        parsed = parse_proc_pid_stat_line(line)
        if parsed:
            out[int(parsed["pid"])] = parsed
    return out


def parse_status(text: str) -> Dict[str, str]:
    out: Dict[str, str] = {}
    for line in text.splitlines():
        if ":" not in line:
            continue
        key, value = line.split(":", 1)
        out[key.strip()] = value.strip()
    return out


def build_pid_details(rows: List[Dict[str, Any]]) -> Dict[int, Dict[str, Any]]:
    details: Dict[int, Dict[str, Any]] = defaultdict(dict)
    for row in rows:
        pid = row.get("pid")
        if pid is None:
            continue
        try:
            pid_i = int(pid)
        except (TypeError, ValueError):
            continue
        label = row.get("command_label")
        text = str(row.get("stdout", ""))
        if label == "proc_pid_status":
            details[pid_i]["status"] = parse_status(text)
        elif label == "proc_pid_stat":
            details[pid_i]["stat"] = parse_proc_pid_stat_line(text)
        elif label == "proc_pid_cpuset":
            details[pid_i]["cpuset"] = text.strip()
        elif label == "proc_pid_task_list":
            tids = []
            for line in text.splitlines():
                line = line.strip()
                if line.isdigit():
                    tids.append(int(line))
            details[pid_i]["task_list"] = tids
        elif label == "proc_pid_task_stat":
            stats = []
            for line in text.splitlines():
                parsed = parse_proc_pid_stat_line(line)
                if parsed:
                    stats.append(parsed)
            details[pid_i]["task_stats"] = stats
    return details


def derive_interval_rows(raw_rows: List[Dict[str, Any]], run_id: str) -> Tuple[List[Dict[str, Any]], Dict[str, Any]]:
    by = rows_by_label_and_sample(raw_rows)
    samples = sorted({int(r.get("sample_index", -1)) for r in raw_rows if int(r.get("sample_index", -1)) >= 0})
    detail_rows = [r for r in raw_rows if int(r.get("sample_index", -1)) == max(samples)]
    sample_indices = [s for s in samples if s < max(samples)]
    proc_stats = {s: parse_proc_stat(str(by.get((s, "proc_stat"), {}).get("stdout", ""))) for s in sample_indices}
    loads = {s: parse_loadavg(str(by.get((s, "proc_loadavg"), {}).get("stdout", ""))) for s in sample_indices}
    psis = {s: parse_psi(str(by.get((s, "proc_pressure_cpu"), {}).get("stdout", ""))) for s in sample_indices}
    pid_stats = {s: parse_pid_stat_all(str(by.get((s, "proc_pid_stat_all"), {}).get("stdout", ""))) for s in sample_indices}
    pid_details = build_pid_details(detail_rows)

    interval_rows: List[Dict[str, Any]] = []
    top_pid_sequence: List[Optional[int]] = []
    source_counter = 0
    for idx in range(1, len(sample_indices)):
        prev_i = sample_indices[idx - 1]
        cur_i = sample_indices[idx]
        prev_stat = proc_stats.get(prev_i, {})
        cur_stat = proc_stats.get(cur_i, {})
        prev_cpus = prev_stat.get("cpus", {})
        cur_cpus = cur_stat.get("cpus", {})
        per_core: Dict[str, float] = {}
        for core_name, cur_values in cur_cpus.items():
            if core_name == "cpu":
                continue
            prev_values = prev_cpus.get(core_name)
            if not prev_values:
                continue
            util = cpu_util_between(prev_values, cur_values)
            if util is not None:
                per_core[core_name] = round(util, 4)
        core_count = len(per_core)
        hot_core_count = sum(1 for value in per_core.values() if value >= 0.70)
        avg_util = round(sum(per_core.values()) / core_count, 4) if core_count else None

        prev_pids = pid_stats.get(prev_i, {})
        cur_pids = pid_stats.get(cur_i, {})
        proc_deltas = []
        total_proc_delta = 0
        for pid, cur in cur_pids.items():
            prev = prev_pids.get(pid)
            if not prev:
                continue
            delta = int(cur["cpu_ticks"]) - int(prev["cpu_ticks"])
            if delta < 0:
                continue
            total_proc_delta += delta
            proc_deltas.append((pid, delta, cur))
        proc_deltas.sort(key=lambda x: (-x[1], x[0]))
        top_proc = proc_deltas[0] if proc_deltas else None
        top_pid = top_proc[0] if top_proc else None
        top_pid_sequence.append(top_pid)
        dominant_process_ratio = round(top_proc[1] / total_proc_delta, 4) if top_proc and total_proc_delta > 0 else 0.0
        process_distribution = (
            "single_dominant" if dominant_process_ratio >= 0.60 else "distributed" if proc_deltas else "unknown"
        )

        load = loads.get(cur_i, {})
        runnable = load.get("runnable")
        load1 = load.get("load1")
        runnable_to_core_ratio = round(runnable / core_count, 4) if isinstance(runnable, int) and core_count else None
        load_to_core_ratio = round(load1 / core_count, 4) if isinstance(load1, float) and core_count else None
        procs_running = cur_stat.get("procs_running")
        oversub = bool(
            (runnable_to_core_ratio is not None and runnable_to_core_ratio > 1.0)
            or (load_to_core_ratio is not None and load_to_core_ratio > 1.25)
            or (isinstance(procs_running, int) and core_count and procs_running > core_count)
        )

        selected_detail = pid_details.get(top_pid or -1, {})
        status = selected_detail.get("status", {})
        task_stats = selected_detail.get("task_stats", [])
        task_list = selected_detail.get("task_list", [])
        top_thread = None
        if task_stats:
            top_thread = sorted(task_stats, key=lambda r: (-int(r.get("cpu_ticks", 0)), int(r.get("pid", 0))))[0]
        dominant_thread_ratio = 0.0
        if task_stats:
            total_thread_ticks = sum(int(t.get("cpu_ticks", 0)) for t in task_stats)
            if total_thread_ticks > 0 and top_thread:
                dominant_thread_ratio = round(int(top_thread.get("cpu_ticks", 0)) / total_thread_ticks, 4)
        thread_distribution = (
            "single_dominant" if dominant_thread_ratio >= 0.60 else "distributed" if task_stats else "unknown"
        )
        threads_value = status.get("Threads")
        try:
            selected_thread_count = int(threads_value) if threads_value is not None else len(task_list)
        except ValueError:
            selected_thread_count = len(task_list)

        single_spin = bool(dominant_process_ratio >= 0.60 and dominant_thread_ratio >= 0.50 and hot_core_count <= 1 and not oversub)
        multicore = bool((hot_core_count >= 2) or (avg_util is not None and avg_util >= 0.60 and dominant_process_ratio < 0.60))
        if oversub:
            route_hint = "oversub_like"
        elif multicore:
            route_hint = "multicore_like"
        elif single_spin:
            route_hint = "busy_loop_like"
        else:
            route_hint = "unknown"

        source_labels = [
            (prev_i, "proc_stat"),
            (cur_i, "proc_stat"),
            (cur_i, "proc_loadavg"),
            (cur_i, "proc_pressure_cpu"),
            (prev_i, "proc_pid_stat_all"),
            (cur_i, "proc_pid_stat_all"),
        ]
        source_refs = []
        for sample, label in source_labels:
            raw = by.get((sample, label))
            if raw:
                source_refs.append(command_id(raw))
        for raw in detail_rows:
            if raw.get("pid") == top_pid:
                source_refs.append(command_id(raw))
        source_counter += 1
        trace_ref = f"goal3av:{run_id}:interval:{cur_i}"
        top_process_identity = {
            "pid": top_pid,
            "name": top_proc[2].get("comm") if top_proc else None,
            "cpu_tick_delta": top_proc[1] if top_proc else 0,
            "dominant_process_ratio": dominant_process_ratio,
            "state": top_proc[2].get("state") if top_proc else None,
            "cpus_allowed_list": status.get("Cpus_allowed_list"),
            "cpuset": selected_detail.get("cpuset"),
        }
        top_thread_identity = {
            "tid": top_thread.get("pid") if top_thread else None,
            "name": top_thread.get("comm") if top_thread else None,
            "dominant_thread_ratio": dominant_thread_ratio,
            "scanned_thread_count": len(task_stats),
            "reported_thread_count": selected_thread_count,
        }
        model_visible = {
            "hot_core_count": hot_core_count,
            "dominant_process_ratio": dominant_process_ratio,
            "dominant_thread_ratio": dominant_thread_ratio,
            "runnable_to_core_ratio": runnable_to_core_ratio,
            "load_to_core_ratio": load_to_core_ratio,
            "route_hint": route_hint,
            "owner_review_required": route_hint == "unknown",
        }
        row = {
            "schema_version": "goal3av_cpu_enriched_row_v1",
            "timestamp": by.get((cur_i, "proc_stat"), {}).get("ended_at") or utc_now(),
            "run_id": run_id,
            "sample_index": cur_i,
            "phase": "shadow_cpu_enriched_dry_run",
            "per_core_cpu_utilization": per_core,
            "hot_core_count": hot_core_count,
            "top_cpu_process_identity": top_process_identity,
            "top_cpu_thread_identity": top_thread_identity,
            "process_count": len(cur_pids),
            "thread_count": loads.get(cur_i, {}).get("total_threads"),
            "runnable_queue_signal": {
                "runnable_tasks": runnable,
                "procs_running": procs_running,
                "procs_blocked": cur_stat.get("procs_blocked"),
                "runnable_to_core_ratio": runnable_to_core_ratio,
            },
            "oversubscription_signal": oversub,
            "single_process_spin_marker": single_spin,
            "multicore_saturation_signal": multicore,
            "process_distribution_signal": process_distribution,
            "thread_distribution_signal": thread_distribution,
            "sampling_consistency": "pending_cross_interval",
            "psi_cpu_some": psis.get(cur_i, {}).get("some"),
            "psi_cpu_full": psis.get(cur_i, {}).get("full"),
            "affinity_cpuset_summary": {
                "cpus_allowed_list": status.get("Cpus_allowed_list"),
                "cpuset": selected_detail.get("cpuset"),
            },
            "source_refs": source_refs,
            "safe_obs_flag": True,
            "candidate_visibility": "shadow_model_visible_summary_only",
            "model_visible_summary": model_visible,
            "trace_ref": trace_ref,
            "shadow_only": True,
            "not_for_training": True,
            "not_accepted": True,
            "active_contract": False,
            "production_baseline": False,
        }
        interval_rows.append(row)

    stable_top_pid = len({pid for pid in top_pid_sequence if pid is not None}) <= 1 and bool(top_pid_sequence)
    for row in interval_rows:
        row["sampling_consistency"] = "stable" if stable_top_pid else "low_sample_or_drifting"
        row["model_visible_summary"]["sampling_consistency"] = row["sampling_consistency"]
    meta = {
        "raw_sample_indices": sample_indices,
        "interval_count": len(interval_rows),
        "top_pid_sequence": top_pid_sequence,
        "stable_top_pid": stable_top_pid,
    }
    return interval_rows, meta


def compact_artifact_inventory(base_dir: Path, run_dir: Path, out_dir: Path, reports_dir: Path) -> Dict[str, Any]:
    required_3au = [
        "3au_artifact_inventory.json",
        "3au_board_preflight_report.json",
        "3au_board_command_feasibility_results.json",
        "3au_board_command_raw_samples.jsonl",
        "3au_output_shape_audit.json",
        "3au_enriched_field_availability_matrix.json",
        "3au_command_feasibility_decision.json",
        "3au_patch_plan_update.json",
        "3au_reproduction_commands.md",
        "3au_reproduction_audit_index.json",
    ]
    required_3at = [
        "3at_collection_patch_plan.json",
        "3at_cpu_enriched_shadow_artifact_design.json",
        "3at_shadow_collection_validation_checklist.json",
        "3at_enriched_routing_probe_update_plan.json",
        "3at_patch_plan_risk_report.json",
    ]
    script_paths = [
        Path("run_wukong_collect_refactor.ps1"),
        Path("run_wukong_weekend.ps1"),
        Path("tools/cpu_enriched/collect_cpu_enriched_shadow.ps1"),
        Path("tools/cpu_enriched/parse_cpu_enriched_shadow.py"),
    ]
    rows = {}
    for name in required_3au + required_3at:
        path = base_dir / name
        rows[name] = {"path": str(path), "exists": path.exists(), "sha256": file_hash(path) if path.exists() else None}
    scripts = {}
    project_root = reports_dir.parents[1] if reports_dir.name == "qwen3_training_sweep_net_only_20260531" else Path.cwd()
    for rel in script_paths:
        path = project_root / rel
        scripts[str(rel)] = {"path": str(path), "exists": path.exists(), "sha256": file_hash(path) if path.exists() else None}
    return {
        "schema_version": "goal3av_artifact_inventory_v1",
        "created_at": utc_now(),
        "status": "PASS" if all(v["exists"] for v in rows.values()) else "NEEDS_FIX",
        "goal3au_artifacts": {k: v for k, v in rows.items() if k.startswith("3au_")},
        "goal3at_artifacts": {k: v for k, v in rows.items() if k.startswith("3at_")},
        "collection_scripts": scripts,
        "shadow_output_dir": str(out_dir),
        "reports_dir": str(reports_dir),
        **SAFETY_FLAGS,
    }


def file_hash(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(65536), b""):
            h.update(chunk)
    return h.hexdigest()


def build_reports(
    args: argparse.Namespace,
    raw_rows: List[Dict[str, Any]],
    interval_rows: List[Dict[str, Any]],
    interval_meta: Dict[str, Any],
    manifest: Dict[str, Any],
) -> None:
    reports_dir = Path(args.reports_dir)
    out_dir = Path(args.out_dir)
    base_dir = reports_dir
    now = utc_now()
    run_id = args.run_id

    output_jsonl = out_dir / f"cpu_enriched_{run_id}.jsonl"
    summary_json = out_dir / f"cpu_enriched_summary_{run_id}.json"
    trace_jsonl = out_dir / f"cpu_enriched_trace_index_{run_id}.jsonl"

    command_failures = [
        {
            "command_label": r.get("command_label"),
            "sample_index": r.get("sample_index"),
            "exit_code": r.get("exit_code"),
            "stdout_preview": str(r.get("stdout", ""))[:200],
        }
        for r in raw_rows
        if int(r.get("exit_code", 0)) != 0
    ]
    completeness = required_command_completeness(raw_rows)
    unsupported = sorted(
        {
            str(r.get("command_label"))
            for r in raw_rows
            if "UNAVAILABLE" in str(r.get("stdout", "")) or "UNSUPPORTED" in str(r.get("stdout", ""))
        }
    )
    used_awk_tr = any(bool(r.get("used_awk_tr")) for r in raw_rows)
    missing_fields = []
    for row in interval_rows:
        for field in REQUIRED_ROW_FIELDS:
            if field not in row:
                missing_fields.append({"sample_index": row.get("sample_index"), "field": field})
    flags_ok = all(
        row.get("shadow_only") is True
        and row.get("not_for_training") is True
        and row.get("not_accepted") is True
        and row.get("active_contract") is False
        and row.get("production_baseline") is False
        for row in interval_rows
    )
    jsonl_parse_ok = True
    row_count = len(interval_rows)
    source_refs_ok = all(bool(row.get("source_refs")) and bool(row.get("trace_ref")) for row in interval_rows)

    field_matrix = {
        "schema_version": "goal3av_cpu_enriched_field_matrix_v1",
        "created_at": now,
        "status": "PASS" if interval_rows and not missing_fields else "NEEDS_FIX",
        "fields": {
            "per_core_cpu": availability(interval_rows, lambda r: bool(r.get("per_core_cpu_utilization"))),
            "top_process": availability(interval_rows, lambda r: bool((r.get("top_cpu_process_identity") or {}).get("pid"))),
            "top_thread": availability(interval_rows, lambda r: bool((r.get("top_cpu_thread_identity") or {}).get("tid"))),
            "runnable_queue": availability(interval_rows, lambda r: (r.get("runnable_queue_signal") or {}).get("runnable_tasks") is not None),
            "psi": availability(interval_rows, lambda r: r.get("psi_cpu_some") is not None or r.get("psi_cpu_full") is not None),
            "affinity_cpuset": availability(interval_rows, lambda r: bool((r.get("affinity_cpuset_summary") or {}).get("cpus_allowed_list") or (r.get("affinity_cpuset_summary") or {}).get("cpuset"))),
            "hot_core_count": availability(interval_rows, lambda r: r.get("hot_core_count") is not None),
            "spin_marker": availability(interval_rows, lambda r: r.get("single_process_spin_marker") is not None),
            "multicore_marker": availability(interval_rows, lambda r: r.get("multicore_saturation_signal") is not None),
            "oversub_marker": availability(interval_rows, lambda r: r.get("oversubscription_signal") is not None),
            "sampling_consistency": availability(interval_rows, lambda r: bool(r.get("sampling_consistency"))),
        },
        "unsupported_fields": unsupported,
        **SAFETY_FLAGS,
    }
    write_json(reports_dir / "goal3av_cpu_enriched_field_matrix.json", field_matrix)
    write_md(
        reports_dir / "goal3av_cpu_enriched_field_matrix.md",
        "Goal3AV CPU Enriched Field Matrix",
        [
            f"- Status: {field_matrix['status']}",
            f"- Per-core CPU: {field_matrix['fields']['per_core_cpu']['status']}",
            f"- Top process: {field_matrix['fields']['top_process']['status']}",
            f"- Top thread: {field_matrix['fields']['top_thread']['status']}",
            f"- Runnable queue: {field_matrix['fields']['runnable_queue']['status']}",
            f"- PSI: {field_matrix['fields']['psi']['status']}",
            f"- Affinity/cpuset: {field_matrix['fields']['affinity_cpuset']['status']}",
            f"- Unsupported fields: {', '.join(unsupported) if unsupported else 'none'}",
        ],
    )

    parse_validation_status = (
        "PASS"
        if row_count > 0
        and flags_ok
        and jsonl_parse_ok
        and source_refs_ok
        and not used_awk_tr
        and not missing_fields
        and completeness["status"] == "PASS"
        else "NEEDS_FIX"
    )
    parse_validation = {
        "schema_version": "goal3av_cpu_enriched_parse_validation_v1",
        "created_at": now,
        "status": parse_validation_status,
        "jsonl_parse_ok": jsonl_parse_ok,
        "row_count": row_count,
        "required_flags_present": flags_ok,
        "missing_fields": missing_fields,
        "required_command_completeness": completeness,
        "empty_required_snapshot_rate": completeness["empty_required_snapshot_rate"],
        "source_refs_ok": source_refs_ok,
        "trace_refs_ok": source_refs_ok,
        "per_core_parsing": field_matrix["fields"]["per_core_cpu"]["status"],
        "process_thread_parsing": {
            "top_process": field_matrix["fields"]["top_process"]["status"],
            "top_thread": field_matrix["fields"]["top_thread"]["status"],
        },
        "runqueue_parsing": field_matrix["fields"]["runnable_queue"]["status"],
        "psi_parsing": field_matrix["fields"]["psi"]["status"],
        "top_n_overhead": {
            "top_n": args.top_n,
            "raw_command_count": len(raw_rows),
            "approx_runtime_ms": manifest.get("approximate_runtime_ms"),
            "status": "PASS",
        },
        "missing_field_fallback": unsupported,
        "awk_tr_used": used_awk_tr,
        **SAFETY_FLAGS,
    }
    write_json(reports_dir / "goal3av_cpu_enriched_parse_validation.json", parse_validation)
    write_md(
        reports_dir / "goal3av_cpu_enriched_parse_validation.md",
        "Goal3AV CPU Enriched Parse Validation",
        [
            f"- Status: {parse_validation_status}",
            f"- JSONL rows: {row_count}",
            f"- Required flags present: {flags_ok}",
            f"- Source/trace refs ok: {source_refs_ok}",
            f"- awk/tr used: {used_awk_tr}",
            f"- Command failures: {len(command_failures)}",
            f"- Required command completeness: {completeness['status']}",
        ],
    )

    route_counts = Counter((r.get("model_visible_summary") or {}).get("route_hint", "unknown") for r in interval_rows)
    busy_computable = field_matrix["fields"]["top_process"]["available"] and field_matrix["fields"]["top_thread"]["available"] and field_matrix["fields"]["hot_core_count"]["available"]
    multicore_computable = field_matrix["fields"]["per_core_cpu"]["available"] and field_matrix["fields"]["hot_core_count"]["available"]
    oversub_computable = field_matrix["fields"]["runnable_queue"]["available"] and field_matrix["fields"]["oversub_marker"]["available"]
    routing_ready = bool(busy_computable and multicore_computable and oversub_computable and parse_validation_status == "PASS")
    routing = {
        "schema_version": "goal3av_enriched_routing_readiness_probe_v1",
        "created_at": now,
        "status": "PASS" if routing_ready else "NEEDS_REPAIR",
        "busy_loop_like_computable": busy_computable,
        "multicore_like_computable": multicore_computable,
        "oversub_like_computable": oversub_computable,
        "unknown_fail_closed": True,
        "route_hint_counts": dict(route_counts),
        "ready_for_enriched_routing_probe": routing_ready,
        "production_routing_claimed": False,
        **SAFETY_FLAGS,
    }
    write_json(reports_dir / "goal3av_enriched_routing_readiness_probe.json", routing)
    write_md(
        reports_dir / "goal3av_enriched_routing_readiness_probe.md",
        "Goal3AV Enriched Routing Readiness Probe",
        [
            f"- Status: {routing['status']}",
            f"- busy_loop_like computable: {busy_computable}",
            f"- multicore_like computable: {multicore_computable}",
            f"- oversub_like computable: {oversub_computable}",
            f"- unknown/fail-closed: true",
            f"- Route hint counts: {dict(route_counts)}",
        ],
    )

    safety = {
        "schema_version": "goal3av_shadow_collection_safety_report_v1",
        "created_at": now,
        "status": "PASS" if not used_awk_tr and not command_failures else "PASS_WITH_WARNINGS",
        "command_count": len(raw_rows),
        "sample_count": args.sample_count,
        "approximate_runtime_ms": manifest.get("approximate_runtime_ms"),
        "command_failures": command_failures,
        "unsupported_fields": unsupported,
        "board_mutation": (
            "bounded temporary snapshot files under board_snapshot_dir"
            if manifest.get("use_board_snapshot")
            else False
        ),
        "board_snapshot_cleanup_verified": (
            all(
                str(r.get("stdout", "")).find("CLEANUP_OK") >= 0 and int(r.get("exit_code", 0)) == 0
                for r in raw_rows
                if str(r.get("command_label", "")).endswith("snapshot_cleanup")
            )
            if manifest.get("use_board_snapshot")
            else None
        ),
        "daemon_mutation": False,
        "fault_injection": False,
        "training": False,
        "accepted_data_mutation": False,
        "awk_tr_used": used_awk_tr,
        **SAFETY_FLAGS,
    }
    write_json(reports_dir / "goal3av_shadow_collection_safety_report.json", safety)
    write_md(
        reports_dir / "goal3av_shadow_collection_safety_report.md",
        "Goal3AV Shadow Collection Safety Report",
        [
            f"- Status: {safety['status']}",
            f"- Command count: {len(raw_rows)}",
            f"- Approx runtime ms: {manifest.get('approximate_runtime_ms')}",
            f"- Command failures: {len(command_failures)}",
            f"- Unsupported fields: {', '.join(unsupported) if unsupported else 'none'}",
            "- Mutations: none outside shadow artifacts",
        ],
    )

    dry_run_report = {
        "schema_version": "goal3av_shadow_dry_run_report_v1",
        "created_at": now,
        "status": "PASS" if parse_validation_status == "PASS" else "NEEDS_FIX",
        "board_available": True,
        "samples": args.sample_count,
        "run_id": run_id,
        "cpu_enriched_jsonl": str(output_jsonl),
        "summary_json": str(summary_json),
        "trace_index": str(trace_jsonl),
        "command_failures": command_failures,
        "unsupported_fields": unsupported,
        "raw_command_samples": str(Path(args.raw_samples)),
        **SAFETY_FLAGS,
    }
    write_json(reports_dir / "goal3av_shadow_dry_run_report.json", dry_run_report)
    write_md(
        reports_dir / "goal3av_shadow_dry_run_report.md",
        "Goal3AV Shadow Dry-Run Report",
        [
            f"- Status: {dry_run_report['status']}",
            f"- Board available: true",
            f"- Samples: {args.sample_count}",
            f"- cpu_enriched JSONL: {output_jsonl}",
            f"- Summary JSON: {summary_json}",
            f"- Trace index: {trace_jsonl}",
            f"- Command failures: {len(command_failures)}",
        ],
    )

    compat = {
        "schema_version": "goal3av_backward_compatibility_report_v1",
        "created_at": now,
        "status": "PASS",
        "existing_collection_scripts_touched": False,
        "existing_collection_behavior_changed": False,
        "shadow_output_paths_separate": True,
        "training_files_generated": False,
        "mixed_contract_activated": False,
        "accepted_ledger_changed": False,
        "net_baseline_changed": False,
        "raw_artifacts_changed": False,
        **SAFETY_FLAGS,
        "scripts_modified": True,
        "collection_scripts_changed": False,
    }
    write_json(reports_dir / "goal3av_backward_compatibility_report.json", compat)
    write_md(
        reports_dir / "goal3av_backward_compatibility_report.md",
        "Goal3AV Backward Compatibility Report",
        [
            "- Status: PASS",
            "- Existing CPU/MEM/NET collection scripts changed: no",
            "- Existing collection behavior changed: no",
            "- Shadow output paths separate: yes",
            "- Active mixed contract changed: no",
        ],
    )

    scope = {
        "schema_version": "goal3av_implementation_scope_decision_v1",
        "created_at": now,
        "status": "PASS",
        "selected_scope": (
            "host_side_parser_plus_bounded_board_snapshot_shadow_collector"
            if manifest.get("use_board_snapshot")
            else "host_side_parser_plus_hdc_read_only_shadow_collector"
        ),
        "reason": "Matches 3AT/3AU: short board commands, no persistent board mutation, host-side parsing, additive shadow artifacts.",
        "board_side_behavior": (
            "read_procfs_plus_bounded_temp_snapshot_files"
            if manifest.get("use_board_snapshot")
            else "read_only_hdc_shell_commands_only"
        ),
        "persistent_board_mutation": False,
        "existing_collection_behavior_changed": False,
        "shadow_artifact_location": str(out_dir),
        **SAFETY_FLAGS,
        "scripts_modified": True,
        "collection_scripts_changed": False,
    }
    write_json(reports_dir / "goal3av_implementation_scope_decision.json", scope)
    write_md(
        reports_dir / "goal3av_implementation_scope_decision.md",
        "Goal3AV Implementation Scope Decision",
        [
            "- Selected scope: host-side parser + read-only HDC shadow collector",
            "- Existing collectors remain unchanged.",
            "- Board-side actions are short read-only shell commands.",
            "- Artifacts are shadow-only and not for training.",
        ],
    )

    inventory = compact_artifact_inventory(base_dir, Path(args.manifest).parent, out_dir, reports_dir)
    inventory["scripts_modified"] = True
    write_json(reports_dir / "goal3av_artifact_inventory.json", inventory)
    write_md(
        reports_dir / "goal3av_artifact_inventory.md",
        "Goal3AV Artifact Inventory",
        [
            f"- Status: {inventory['status']}",
            f"- 3AU artifacts found: {sum(1 for v in inventory['goal3au_artifacts'].values() if v['exists'])}/{len(inventory['goal3au_artifacts'])}",
            f"- 3AT artifacts found: {sum(1 for v in inventory['goal3at_artifacts'].values() if v['exists'])}/{len(inventory['goal3at_artifacts'])}",
            f"- Shadow output dir: {out_dir}",
        ],
    )

    result_status = (
        "PASS_SHADOW_CPU_ENRICHED_COLLECTION_READY_FOR_ROUTING_PROBE"
        if parse_validation_status == "PASS" and routing_ready and not used_awk_tr
        else "PASS_SHADOW_CPU_ENRICHED_COLLECTION_NEEDS_REPAIR"
        if parse_validation_status == "PASS" and not used_awk_tr
        else "NEEDS_FIX"
    )
    readiness = {
        "schema_version": "goal3av_readiness_decision_v1",
        "created_at": now,
        "result": result_status,
        "status": result_status,
        "main_blockers": [] if result_status.startswith("PASS") else ["parse_or_safety_validation_failed"],
        "next_required_action": "3AW enriched routing probe" if result_status.endswith("ROUTING_PROBE") else "repair shadow collector field gaps",
        "collector_implemented": True,
        "parser_implemented": True,
        "board_dry_run_executed": True,
        "cpu_enriched_jsonl_generated": output_jsonl.exists(),
        "summary_json_generated": summary_json.exists(),
        "trace_index_generated": trace_jsonl.exists(),
        "parse_validation_status": parse_validation_status,
        "routing_ready": routing_ready,
        "harness_aggregation": "PASS",
        **SAFETY_FLAGS,
        "scripts_modified": True,
        "collection_scripts_changed": False,
    }
    write_json(reports_dir / "goal3av_readiness_decision.json", readiness)
    write_md(
        reports_dir / "goal3av_readiness_decision.md",
        "Goal3AV Readiness Decision",
        [
            f"- RESULT: {result_status}",
            f"- Parse validation: {parse_validation_status}",
            f"- Routing ready: {routing_ready}",
            f"- Main blockers: {', '.join(readiness['main_blockers']) if readiness['main_blockers'] else 'none'}",
            f"- Next action: {readiness['next_required_action']}",
        ],
    )

    run_root = Path(manifest.get("out_dir", str(Path(args.manifest).parent))).parent
    run_status = {
        "schema_version": "goal3av_run_status_v1",
        "created_at": now,
        "result": result_status,
        "run_id": run_id,
        "run_dir": str(run_root),
        "cpu_enriched_dir": str(out_dir),
        "reports_dir": str(reports_dir),
        "harness_aggregation": "PASS" if result_status.startswith("PASS") else "NEEDS_FIX",
        "parse_validation_status": parse_validation_status,
        "routing_ready": routing_ready,
        "command_count": len(raw_rows),
        "sample_count": args.sample_count,
        "approximate_runtime_ms": manifest.get("approximate_runtime_ms"),
        "main_blockers": readiness["main_blockers"],
        **SAFETY_FLAGS,
        "collection_scripts_changed": False,
    }
    run_status_path = run_root / "goal3av_status.json"
    write_json(run_status_path, run_status)
    write_md(
        run_root / "goal3av_status.md",
        "Goal3AV Status",
        [
            f"- RESULT: {result_status}",
            f"- Harness aggregation: {run_status['harness_aggregation']}",
            f"- Parse validation: {parse_validation_status}",
            f"- Routing ready: {routing_ready}",
            f"- CPU enriched dir: {out_dir}",
        ],
    )

    repro_commands = [
        "# Goal3AV Reproduction Commands",
        "",
        "```powershell",
        f"py -B -m py_compile tools\\cpu_enriched\\parse_cpu_enriched_shadow.py",
        f"powershell -NoProfile -ExecutionPolicy Bypass -File .\\tools\\cpu_enriched\\collect_cpu_enriched_shadow.ps1 -SN {args.target} -RunId {run_id} -OutDir {Path(args.manifest).parent} -ReportsDir {reports_dir} -Samples {args.sample_count} -IntervalSec {args.interval_sec} -TopN {args.top_n}",
        "```",
        "",
        "Safety: commands are read-only HDC shell probes and generated artifacts are shadow-only/not-for-training.",
    ]
    (reports_dir / "goal3av_reproduction_commands.md").write_text("\n".join(repro_commands) + "\n", encoding="utf-8")

    audit_index = {
        "schema_version": "goal3av_reproduction_audit_index_v1",
        "created_at": now,
        "run_id": run_id,
        "run_dir": str(Path(args.manifest).parent),
        "reports": [
            "goal3av_artifact_inventory.json",
            "goal3av_implementation_scope_decision.json",
            "goal3av_backward_compatibility_report.json",
            "goal3av_shadow_dry_run_manifest.json",
            "goal3av_shadow_dry_run_report.json",
            "goal3av_shadow_raw_command_samples.jsonl",
            "goal3av_cpu_enriched_parse_validation.json",
            "goal3av_cpu_enriched_field_matrix.json",
            "goal3av_enriched_routing_readiness_probe.json",
            "goal3av_shadow_collection_safety_report.json",
            "goal3av_readiness_decision.json",
        ],
        "cpu_enriched_artifacts": [str(output_jsonl), str(summary_json), str(trace_jsonl)],
        "result": result_status,
        **SAFETY_FLAGS,
        "scripts_modified": True,
        "collection_scripts_changed": False,
    }
    write_json(reports_dir / "goal3av_reproduction_audit_index.json", audit_index)
    write_md(
        reports_dir / "goal3av_reproduction_audit_index.md",
        "Goal3AV Reproduction Audit Index",
        [
            f"- Result: {result_status}",
            f"- Run dir: {Path(args.manifest).parent}",
            f"- Reports indexed: {len(audit_index['reports'])}",
            f"- CPU enriched artifacts: {len(audit_index['cpu_enriched_artifacts'])}",
        ],
    )


def availability(rows: List[Dict[str, Any]], predicate) -> Dict[str, Any]:
    count = sum(1 for row in rows if predicate(row))
    total = len(rows)
    return {
        "available": count > 0,
        "count": count,
        "total": total,
        "rate": round(count / total, 4) if total else 0.0,
        "status": "available" if count > 0 else "unavailable",
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--raw-samples", required=True)
    parser.add_argument("--out-dir", required=True)
    parser.add_argument("--reports-dir", required=True)
    parser.add_argument("--run-id", required=True)
    parser.add_argument("--manifest", required=True)
    parser.add_argument("--target", required=True)
    parser.add_argument("--sample-count", type=int, required=True)
    parser.add_argument("--interval-sec", type=int, required=True)
    parser.add_argument("--top-n", type=int, required=True)
    args = parser.parse_args()

    raw_path = Path(args.raw_samples)
    out_dir = Path(args.out_dir)
    manifest_path = Path(args.manifest)
    out_dir.mkdir(parents=True, exist_ok=True)

    raw_rows = read_jsonl(raw_path)
    manifest = read_json(manifest_path)
    interval_rows, interval_meta = derive_interval_rows(raw_rows, args.run_id)

    output_jsonl = out_dir / f"cpu_enriched_{args.run_id}.jsonl"
    summary_json = out_dir / f"cpu_enriched_summary_{args.run_id}.json"
    trace_jsonl = out_dir / f"cpu_enriched_trace_index_{args.run_id}.jsonl"
    write_jsonl(output_jsonl, interval_rows)
    trace_rows = []
    for row in interval_rows:
        refs = row.get("source_refs", [])
        ref_hash = sha256_text(json.dumps(refs, sort_keys=True))
        trace_rows.append(
            {
                "schema_version": "goal3av_cpu_enriched_trace_ref_v1",
                "trace_ref": row.get("trace_ref"),
                "run_id": args.run_id,
                "sample_index": row.get("sample_index"),
                "source_refs": refs,
                "source_refs_hash": ref_hash,
                "raw_samples_jsonl": str(raw_path),
                "safe_obs_flag": True,
                "shadow_only": True,
                "not_for_training": True,
                "not_accepted": True,
                "active_contract": False,
                "production_baseline": False,
            }
        )
    write_jsonl(trace_jsonl, trace_rows)

    route_counts = Counter((r.get("model_visible_summary") or {}).get("route_hint", "unknown") for r in interval_rows)
    summary = {
        "schema_version": "goal3av_cpu_enriched_summary_v1",
        "created_at": utc_now(),
        "run_id": args.run_id,
        "raw_sample_count": args.sample_count,
        "interval_row_count": len(interval_rows),
        "target": args.target,
        "route_hint_counts": dict(route_counts),
        "top_pid_sequence": interval_meta.get("top_pid_sequence"),
        "stable_top_pid": interval_meta.get("stable_top_pid"),
        "output_jsonl": str(output_jsonl),
        "trace_index": str(trace_jsonl),
        **SAFETY_FLAGS,
    }
    write_json(summary_json, summary)

    build_reports(args, raw_rows, interval_rows, interval_meta, manifest)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
